# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: npm # See documentation for possible values
    directory: /packages/core # Location of package manifests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: npm # See documentation for possible values
    directory: /packages/docs # Location of package manifests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: npm # See documentation for possible values
    directory: /packages/gitmars # Location of package manifests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: npm # See documentation for possible values
    directory: /packages/server # Location of package manifests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: npm # See documentation for possible values
    directory: /packages/ui # Location of package manifests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'aws*'
      - dependency-name: typescript
        versions: [4.x]
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
